database:
  path: ./data/ra_tracker.db
scheduler:
  event_horizon_days: 100
  fetch_interval_hours: 6
telegram:
  bot_token: 8200624905:AAFcNY1sdCHpakoVbeJBh6PQvFon3xfxxac
  chat_id: '769647676'
user:
  local_area_id: 34
  local_area_name: Berlin
web:
  host: 0.0.0.0
  port: 8080

# Email notification settings 
email:
  server: smtp-relay.brevo.com
  port: 587
  username: "${BREVO_SMTP_USERNAME}"
  password: "${BREVO_SMTP_PASSWORD}"
  from_address: "ravetracker@whotrustswho.com"
  from_name: "Rave Tracker"
  starttls: true
  ssl_tls: false

app:
  secret_key: "${SECRET_KEY}"
  base_url: "${BASE_URL}"
